# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available) to the container
COPY package*.json ./

# Install dependencies
RUN npm install
# If you're using nodemon for development, install it globally in the container
RUN npm install -g nodemon

# Copy the rest of your application's code
COPY . .

# Expose the port on which your app will run
EXPOSE 3000

# Define the command to run your app using nodemon
CMD ["nodemon", "index.js"]